### ISSUE TITLE
Can this project import OPC-UA XML?

### ISSUE THREAD

**Issue by maul5** [eclipse/milo#124]
Hello,

I want to know if the tool generated XML can be used in "milo".

the tool is opcus-modeler(https://github.com/FreeOpcUa/opcua-modeler).

Thank you very much.

**Comment by kevinherron** [comment]
I am working on [this project](https://github.com/digitalpetri/uanodeset-parser) which will make it possible, but the API is not stable yet.

I cannot include this functionality directly in Milo because of some restrictions by the Eclipse Foundation IP review team about the use of the UANodeSet and other XML files.

**Comment by maul5** [comment]
Thank you for answer the letter

I will try this project. ^^

**Comment by kevinherron** [comment]
There's no example yet, but hopefully soon.

Please use the mailing list or gitter.im channel for questions and save the GH issue tracker for bug reports.
