### ISSUE TITLE
Client ID can be null

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#134]
I think there is an issue handling `null` client IDs. From what I know (and I may be wrong here) client IDs may be `null` when requesting a subscription.

And currently this works fine in Milo with the exception of handling the server result after the subscriptions succeeded:

[OpcUaSubscription.java:130](https://github.com/eclipse/milo/blob/master/opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java#L130)
```java
if (item.getStatusCode().isGood()) {
  itemsByClientHandle.put(item.getClientHandle(), item);
  itemsByServerHandle.put(item.getMonitoredItemId(), item);
}
```

I think this could be fixed with ignoring `null` client IDs altogether in this case.

**Comment by kevinherron** [comment]
I don't think this is actually possible except for if you explicitly created an item client side and fed it a null value. The binary decoder doesn't decode null values for number types, so it's not possible for a null UInteger to have come from the server. Same problem with PR #126

**Comment by ctron** [comment]
Yes, so you can create a subscription with a null ID. Which works since you don't really need that if you set a listener immediately. So you can omit the client ID at all.

**Comment by kevinherron** [comment]
I'm not following what you're trying to say here. Are we talking about the `clientHandle` belonging to a monitored item? This can't be null unless you erroneously tried to create a monitored item with a null value for that parameter.

**Comment by ctron** [comment]
So yes, you can provide null and it will fail only in the location I initially posted. So all the server side code and the Milo code in the middle seems to succeed. It will only fail when handling the server result in the milo sdk-client.

However I think that providing a null client ID is not an error.

**Comment by kevinherron** [comment]
There is no scenario where creating a monitored item and providing a null clientHandle in the `MonitoredItemCreateRequest` is the correct behavior. It happens to not blow up earlier than the code you're pointing out because of how serializers work. And as far as the server is concerned, every value you create in the client with null is actually clientHandle=0, and it's also likely an error to use any duplicate clientHandle values.

You have to imagine that for every generated structure that yes, it's technically possible to set any of the fields to null, but you're not supposed to. It's too cumbersome to check every access to every field though. For at least the numeric types, the assumption is that they will never be null because the specification provides default values for these types.

**Comment by ctron** [comment]
> There is no scenario where creating a monitored item and providing a null clientHandle in the MonitoredItemCreateRequest is the correct behavior.

After digging a bit into the issue and into the OPC UA code at https://github.com/OPCFoundation/UA-.NET/blob/master/Stack/Core/Stack/Generated/Opc.Ua.Client.cs#L2807 I think you are right, the `clientHandle` should never be null.

But that isn't obvious from the API of Milo. So I would suggest to either directly check for null in the constructor or at least add some JavaDoc for that.

**Comment by kevinherron** [comment]
In the next version of my code generator I'll try to put `@Nonnull` annotations on any of the parameters I can determine shouldn't ever be null.
