### ISSUE TITLE
How to read data from Prosys OPC UA simulation server

### ISSUE THREAD

**Issue by austindsouza** [eclipse/milo#169]
Hi, 

I am new to OPC UA world, and understanding the concepts of OPC UA. I have run some examples in Milo project, now to explore more of it in real world scenario, I have installed Prosys OPC UA server for simulation.

When I tried to read the simulated data using Milo client ReadExample by changing the endpoints as obtained by simulation server in ExampleRunner file I see only the server status and timestamp details printing in console.

Can any one help me where I'm doing wrong.

Thanks in advance
Austin

**Comment by kevinherron** [comment]
`ReadExample` only reads the server status and timestamp.

Every Node in an OPC UA server has a NodeId that identifies it. In order to do anything concerning that node (read, write, subscribe, etc...) you need to specify that NodeId.

If you wanted to read simulation values from the server you'd need to modify the example so it reads the NodeIds belonging to simulation nodes.
