### ISSUE TITLE
How to know socket of OpcUaClient session is closed?

### ISSUE THREAD

**Issue by frankiezdh** [eclipse/milo#325]
Are there some Event/Callback/Listener when socket of OpcUaClient session is closed ? 

Consider this scenario：While  OPC UA session is connected,  unplug the network cable.  

I have tried using below methods, but didn't work.
- `org.eclipse.milo.opcua.sdk.client.OpcUaClient#addSessionActivityListener`
- `org.eclipse.milo.opcua.sdk.client.OpcUaClient#addFaultListener`

**Comment by kevinherron** [comment]
@TTia is correct.

The closest thing you have is a SessionActivityListener.

Because of the way TCP works there can sometimes be a delay before the connection loss is detected. The current recommendation is to implement some kind of "keep alive" yourself by reading, for example, the server's CurrentTime and State nodes.

In 0.3 I've actually implemented this keep alive in the FSM that manages the session.

Even in 0.3 you'll still just receive the callback that your session is active or inactive.

**Comment by frankiezdh** [comment]
@TTia @kevinherron Thank you. You guys are awsome!

**Comment by Sidamor** [comment]
> FSM
hi ~
has the "keep alive" been implemented?
or i still neet to implement the "keep alive" myselft by reading such as "Server_State"..?

**Comment by kevinherron** [comment]
@Sidamor a keep alive mechanism as part of the session FSM is implemented in the `dev/0.3` branch. It's something you need to do by yourself in `0.2.x`. Reading the server state and/or time is a good approach.
