### ISSUE TITLE
Add a CI for all master commits

### ISSUE THREAD

**Issue by joesan** [eclipse/milo#457]
Using some CI tool, we could add some auto builds - For a starting point, we could do the following:

1. Run code test coverage metrics from a CI build, push code coverage results to codacy
2. Push snapshot builds to central sonatype snapshot repo. 

Does this make sense? We could use travis for this purpose. I can implement this! Let me know!

**Comment by joesan** [comment]
Ok I just realized that snapshots are pushed via a mvn deploy command and profiles as I can see it from the pom.xml! So please let me know if this issue makes any sense!

**Comment by kevinherron** [comment]
There is already CI in place. Commits to master are tested and deployed, PRs are tested and the status is reported on the PR. Not interested in code coverage right now, especially because a lot of tests are integration tests that cover multiple modules and the coverage tools have a hard time measuring that correctly.

https://ci.eclipse.org/milo

**Comment by joesan** [comment]
Good to know! I was unaware that Eclipse had a central Jenkins CI server! Where is the Jenkinsfile located?

**Comment by kevinherron** [comment]
The jobs are configured on Jenkins rather than by a file in this repo like with Travis CI.

I was previously using Travis CI but it was much slower and less reliable.
