### ISSUE TITLE
opcua install problem

### ISSUE THREAD

**Issue by sds1vrk** [eclipse/milo#492]
Dear Milo Developer

Hello, I am a college student in IT department in Korea. 
I have some difficulties using Milo, so I leave a question.

1. Running it using MILO's OPCUA example, Server and Client, will run in the same space, local, but will cause problems if the server runs in the window and the client runs in uuntu. Entering the ip of the server from the client source causes the same problem. Do you know the solution?

2. I would like to connect with my REST Client using the Milo Server you suggested. In this case, Milo is currently using HTTPS. If I use HTTPS's client to attach it to the Milo server, the following error occurs. Do you know the solution?

3. Can both server and client support both tcp and https, which are examples of Milo now?

4. Finally, is the opcua running the tcp and https separately? Or is the https protocol running on the tcp socket?

I'd appreciate your reply.

![opcua 에러](https://user-images.githubusercontent.com/51287886/58760079-385c9880-856e-11e9-9817-1024f5de2083.PNG)

**Comment by kevinherron** [comment]
The client examples are self-contained. Each of them start a server and stop it when finished. You shouldn't start the provided example server when playing with the client examples. If you're running the example server on a different computer you would have to modify the client examples so they connected to that server and didn't start their own. 

An easier approach would be to run the example server and test with another client, like UaExpert.

HTTPS is just used as a transport layer, the client application on the other side still needs to be an OPC UA client. You can't treat it like a generic REST API or use a HTTP/REST client.

The client and server both support TCP and HTTPS transports at the same time. Only the binary encoding over HTTPS transport is implemented. None of the client examples are set up to use HTTPS transport because it's not very commonly used.

Please use the [https://dev.eclipse.org/mailman/listinfo/milo-dev](https://dev.eclipse.org/mailman/listinfo/milo-dev) for general questions and help in the future.
