### ISSUE TITLE
Prosys OPC UA client Events reading

### ISSUE THREAD

**Issue by AngelThread** [eclipse/milo#533]
Hi,

Thank you for the all the effort, appreciated.

I am new to Milo and I was trying to get familiar with Events by running ExampleServer. What I noticed is that it is possible to read events by UA Expert successfully but it is not the case with Procsys OPC UA client. It is probably related to Procsys client but I had spent some time on this to discover what the case is, before learning it is not the case with UA expert, thanks to @achintya-kumar.
![Can_Not_Read_Events](https://user-images.githubusercontent.com/15628364/63227618-994c5200-c1e8-11e9-877e-f32310707112.PNG)
![Events_Are_Being_Read_Via_UaExpert](https://user-images.githubusercontent.com/15628364/63227619-99e4e880-c1e8-11e9-8b40-2fe3e9425097.PNG)

**Comment by kevinherron** [comment]
Are there any errors in the Prosys client or its logs?

**Comment by kevinherron** [comment]
I looked into this a little more - Prosys client isn't working because the `OfType` FilterOperator is not implemented in Milo. 

You can see in Wireshark that Milo server responds with `Bad_FilterOperatorUnsupported` for the corresponding part of the where clause but it seems the Prosys client doesn't report this in the UI in any way.

I'll see if I can get it implemented for for the 0.4.0 release.

**Comment by kevinherron** [comment]
Closing this, feature can be tracked in #537
