### ISSUE TITLE
How to add OPC UA node to OPC server dynamically while running

### ISSUE THREAD

**Issue by 0DennisLee0** [eclipse/milo#622]
I have known the milo can add the nodes through the XML file, and I wanna know if it works to add node while the server is running?

**Comment by kevinherron** [comment]
If you mean from inside the server, programmatically, yes it's easy: you just add nodes to your NodeManager or otherwise make them available in your AddressSpace implementation.

If you want a client to be able to add nodes you have to implement the NodeManagement services in your AddressSpace. There are not currently any examples of how to do this.

**Comment by 0DennisLee0** [comment]
> If you mean from inside the server, programmatically, yes it's easy: you just add nodes to your NodeManager or otherwise make them available in your AddressSpace implementation.
> 
> If you want a client to be able to add nodes you have to implement the NodeManagement services in your AddressSpace. There are not currently any examples of how to do this.

Thanks for your kind replay~
