### ISSUE TITLE
Subscriptions - display continusely the values of the monitored item

### ISSUE THREAD

**Issue by hbbend** [eclipse/milo#665]
Hello,
I am reading a counter values using opc ua milo client sdk.
I created a subscription to a monitored data item successfully.
I would like to display the values of the counter as it changes.

the ondatachangenotification wont work.
please find the code snippet below:

//***************************
        NotificationListener listener = null;  //i tried  NotificationListener listener = new NotificationListener() but it not possible
        List<DataValue> dataValues = null;
        NotificationMessage notificationMessage = null;

listener.onDataChangeNotification(subscription,items,dataValues,notificationMessage.getPublishTime());
//*****************************		
           
I know that there is something missing, do you have an example how to do this correctly?

Thank you,
Best Regards

**Comment by elucash** [comment]
Are you just calling notification yourself instead of passing a listener to a subscription? It should work the other way around, you implement `NotificationListener` with `onDataChangeNotification` and register it (somewhere, I'm new to _milo_, will find out the details soon) so that `onDataChangeNotification` will be called when there is a change.

**Comment by hbbend** [comment]
just a standard example for that...
