### ISSUE TITLE
Nodeset loading compatibility

### ISSUE THREAD

**Issue by faljse** [eclipse/milo#788]
Tried to load our nodeset with the code mentioned in #713 
Seems to work fine, but in the end the namespace is empty.
Nodes are created and they get added to the namespace, but nothing visible to the client.
Do i need to add a rootnode or sth?
Should this code still be compatible with head?

Our nodeset xml:
https://gist.github.com/faljse/bf698f0ea27953f68ffc274bb2cde9a5

**Comment by kevinherron** [comment]
Hard to say what’s wrong without seeing your code. Did you create a Namespace implementation based on the examples linked to in the nodeset-parser repository? Has that Namespace been added to the server?

What are you expecting your client to see and where are you browsing? Most of these information models just define a bunch of types, which you would only see if you started browsing the type hierarchy from the client. You wouldn’t see instances of these types unless you’ve instantiated and added them yourself.

**Comment by faljse** [comment]
The Nodeset works in open62541;
Rootnode is "Machines" (folder) with "MachineTool1" (object) as child
"MachineTool1" is described in the xml, "Machines" is not.
So could that be the issue; i have to add this root folder manually somehow?

Namespace, etc:
https://gist.github.com/faljse/be5b8a35afbfa2b3dbd5df3761bd206c#file-mynamespace-java
Namespace as seen from open62541:
![image](https://user-images.githubusercontent.com/2340120/110946220-e9e14e00-833e-11eb-8227-4d42dde779e5.png)

**Comment by GoetzGoerisch** [comment]
The _Machines_ folder is defined by the [OPC 40001-1 UA for Machinery 9](https://reference.opcfoundation.org/v104/Machinery/v101/docs/9.1/).
In your addressspace this companion spec is missing.

**Comment by kevinherron** [comment]
This model references THREE other models that you are missing.

**Comment by kevinherron** [comment]
Also I have just updated the ModeledAddressSpace and BacnetNamespace gists for compatibility with the current Milo 0.5.x release.

https://gist.github.com/kevinherron/b4268328c3daeec74343ee82b872aef0
https://gist.github.com/kevinherron/3215a4c624f35fdec0d75faaa442f1b3

**Comment by faljse** [comment]
indeed...  :)
any hints on how to load/merge multiple noadset files?

**Comment by kevinherron** [comment]
Your example also does not need these lines:
```
            DataTypeInitializer.initialize(
                    server.getNamespaceTable(),
                    server.getDataTypeManager()
            );
            ObjectTypeInitializer.initialize(
                    server.getNamespaceTable(),
                    server.getObjectTypeManager()
            );
            VariableTypeInitializer.initialize(
                    server.getNamespaceTable(),
                    server.getVariableTypeManager()
            );
```
In the BacnetNamespace example those are references to initializers that were generated for BACnet types with a prototype code generator. They are not the initializers from the stack and you should not need to do this.

You don't need to merge NodeSet files because you aren't generating code. You should be able to get away with just loading each NodeSet separately, i.e. create a Namespace implementation based on `ModeledAddressSpace` for each of the NodeSets and add them all to your server.

**Comment by faljse** [comment]
Thank you, seems to be working fine now!

**Comment by kevinherron** [comment]
Support for modeling and code generation will take priority hopefully in the near future. I need to add OPC UA 1.04 support first.

**Comment by kevinherron** [comment]
I put together an example server that loads all of these namespaces: https://github.com/kevinherron/machine-example

The models do not define any _instances_, but the Machines folder and others are present.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/340273/110952526-32771800-82fb-11eb-8027-90ac20288898.png">

**Comment by faljse** [comment]
For now we would be very happy if we could connect some VariableNodes from that namespace to an external datasource.
I havent found a read() method or any callbacks in the node itself; so im lost again :(

**Comment by kevinherron** [comment]
Well, the easiest way to hook into the read behavior of a Node is using an AttributeFilter: https://github.com/eclipse/milo/blob/f581575cfbf53e0b7d4528ef0bbd515cf7781930/milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java#L486-L492

This likely will not scale very far though. More efficient read/write must be handled by in your AddressSpace implementation by overriding `AttributeServices::read` and `AttributeServices::write` methods and deciding what the best approach is based on the Node(s) being read or written.

**Comment by GoetzGoerisch** [comment]
Sample Machine Tool Model can be found [here](https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/MachineTool/Machinetool-Example.xml).

**Comment by faljse** [comment]
we need to block in getValue; which is our main issue with single threaded open62541
is this an issue in milo also?

**Comment by kevinherron** [comment]
You can block but it won't scale very well. That is where you need to consider implementing the AddressSpace read/write methods yourself. There is no example of this unfortunately.

**Comment by kevinherron** [comment]
Thank you @GoetzGoerisch. I will see if I can load this model as well. What is your relationship with OPC UA / 62541 / modeling? Always interesting to find others who are working in this area...

**Comment by faljse** [comment]
Does that mean its also only one thread or is there some worker mechanism?

**Comment by GoetzGoerisch** [comment]
https://github.com/GoetzGoerisch/GoetzGoerisch/blob/main/README.md

**Comment by kevinherron** [comment]
No the server uses a thread pool, but if a request to read many nodes comes in and all of the nodes have a blocking AttributeFilter installed then the response may be slow because each AttributeFilter will have getValue called sequentially. 

A smart implementation of your AddressSpace would recognize when Nodes are being read belong to an external source, would know how to batch them together, and would then read the underlying data in some efficient manner and complete then complete the request. Without using an AttributeFilter.

**Comment by kevinherron** [comment]
@GoetzGoerisch your model seems to load 👍 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/340273/110955200-3193b580-82fe-11eb-97d4-ff0429ce2809.png">


However this is where the modeling support in Milo starts to fall apart. Since these instances were loaded from a modeled namespace rather than instantiated in a programmatically created AddressSpace/Namespace there is no easy opportunity to install behavior on the instances as they are created...
