### ISSUE TITLE
Server should accept X.509 certificate chain, instead of only a single certificate

### ISSUE THREAD

**Issue by ctron** [eclipse/milo#870]
**Describe the bug**

Currently the server side of Milo only accepts a single X.509 certificate for e.g. the HTTPS server. However, when the server presents the certificate to the client, it should also present all intermediate certificates, so that the client can find a matching trust anchor.

**Expected behavior**

Allow to provide a full certificate chain instead of a single certificate.

**Additional context**

Milo 0.6.3

**Comment by kevinherron** [comment]
Yes I think this is obviously correct :)

I must want you that the HTTP client/server functionality is essentially untested and unproved, though, so use it at your own risk :) 

Milo only implements the binary encoding and I have not found any demo client/server that implements HTTP transport with the binary encoding rather than XML.
